metadata:
  name: app-config
data:
  app-config.yaml: |
    catalog.http.port: 8080
    connection_string: mongodb://catalog-mongodb:27017
    db_name: catalogdb
    username: mongo
    password: mongo
